/**
 * Generated by tsnapi — public API snapshot of `birpc/sse/client`
 */
// #region Interfaces
export interface SSEChannel {
  post: (_: string) => Promise<void>;
  on: (_: (_: string) => void) => Promise<void>;
}
export interface SSEClientChannelOptions {
  ssePath?: string;
  rpcPath?: string;
  sessionHeader?: string;
  fetch?: typeof globalThis.fetch;
  headers?: Record<string, string>;
}
// #endregion

// #region Functions
export declare function createSseClientChannel(_: string, _?: SSEClientChannelOptions): SSEChannel;
// #endregion
