/**
 * Generated by tsnapi — public API snapshot of `birpc/sse/server`
 */
// #region Interfaces
export interface SSEServerChannel {
  post: (_: string) => Promise<void>;
  on: (_: (_: string) => void) => void;
}
export interface SSESession {
  id: string;
  channel: SSEServerChannel;
  onClose: (_: () => void) => void;
}
export interface SSESessionManager {
  open: (_: IncomingMessage, _: ServerResponse) => SSESession;
  handlePost: (_: IncomingMessage, _: ServerResponse) => Promise<void>;
}
export interface SSESessionManagerOptions {
  sessionHeader?: string;
  generateId?: () => string;
}
// #endregion

// #region Functions
export declare function createSseSessionManager(_?: SSESessionManagerOptions): SSESessionManager;
// #endregion
