/**
 * Generated by tsnapi — public API snapshot of `birpc`
 */
// #region Interfaces
export interface BirpcGroup<RemoteFunctions extends object = Record<string, unknown>, LocalFunctions extends object = Record<string, unknown>, Proxify extends boolean = true> {
  readonly clients: BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>[];
  readonly functions: LocalFunctions;
  readonly broadcast: BirpcGroupReturn<RemoteFunctions, Proxify>;
  updateChannels: (_?: ((_: ChannelOptions[]) => void)) => BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>[];
}
export interface BirpcGroupFn<T> {
  (..._: ArgumentsType<T>): Promise<Awaited<ReturnType<T>>[]>;
  asEvent: (..._: ArgumentsType<T>) => Promise<void>;
}
export interface BirpcGroupReturnBuiltin<RemoteFunctions> {
  $call: <K extends keyof RemoteFunctions>(_: K, ..._: ArgumentsType<RemoteFunctions[K]>) => Promise<Awaited<ReturnType<RemoteFunctions[K]>>[]>;
  $callOptional: <K extends keyof RemoteFunctions>(_: K, ..._: ArgumentsType<RemoteFunctions[K]>) => Promise<(Awaited<ReturnType<RemoteFunctions[K]>> | undefined)[]>;
  $callEvent: <K extends keyof RemoteFunctions>(_: K, ..._: ArgumentsType<RemoteFunctions[K]>) => Promise<void>;
  $callRaw: (_: {
    method: string;
    args: unknown[];
    event?: boolean;
    optional?: boolean;
  }) => Promise<Awaited<ReturnType<any>>[]>;
}
export interface BirpcReturnBuiltin<RemoteFunctions, LocalFunctions = Record<string, unknown>> {
  $functions: LocalFunctions;
  readonly $closed: boolean;
  readonly $meta: any;
  $close: (_?: Error) => void;
  $rejectPendingCalls: (_?: PendingCallHandler) => Promise<void>[];
  $call: <K extends keyof RemoteFunctions>(_: K, ..._: ArgumentsType<RemoteFunctions[K]>) => Promise<Awaited<ReturnType<RemoteFunctions[K]>>>;
  $callOptional: <K extends keyof RemoteFunctions>(_: K, ..._: ArgumentsType<RemoteFunctions[K]>) => Promise<Awaited<ReturnType<RemoteFunctions[K]> | undefined>>;
  $callEvent: <K extends keyof RemoteFunctions>(_: K, ..._: ArgumentsType<RemoteFunctions[K]>) => Promise<void>;
  $callRaw: (_: {
    method: string;
    args: unknown[];
    event?: boolean;
    optional?: boolean;
  }) => Promise<Awaited<ReturnType<any>>[]>;
}
export interface CallRawOptions {
  method: string;
  args: unknown[];
  event?: boolean;
  optional?: boolean;
}
export interface ChannelOptions {
  post: (_: any, ..._: any[]) => Thenable<any>;
  on: (_: (_: any, ..._: any[]) => void) => Thenable<any>;
  off?: (_: (_: any, ..._: any[]) => void) => Thenable<any>;
  serialize?: (_: any) => any;
  deserialize?: (_: any) => any;
  bind?: 'rpc' | 'functions';
  meta?: any;
}
export interface EventOptions<RemoteFunctions extends object = Record<string, unknown>, LocalFunctions extends object = Record<string, unknown>, Proxify extends boolean = true> {
  eventNames?: (keyof RemoteFunctions)[];
  timeout?: number;
  proxify?: Proxify;
  resolver?: BirpcResolver<BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>>;
  onRequest?: (this: BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>, _: RpcRequest, _: (_?: RpcRequest) => Promise<any>, _: (_: any) => void) => void | Promise<void>;
  onFunctionError?: (this: BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>, _: Error, _: string, _: any[]) => boolean | void;
  onGeneralError?: (this: BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>, _: Error, _?: string, _?: any[]) => boolean | void;
  onTimeoutError?: (this: BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>, _: string, _: any[]) => boolean | void;
}
// #endregion

// #region Types
export type BirpcFn<T> = PromisifyFn<T> & {
  asEvent: (..._: ArgumentsType<T>) => Promise<void>;
};
export type BirpcGroupReturn<RemoteFunctions extends object = Record<string, unknown>, Proxify extends boolean = true> = Proxify extends true ? ProxifiedRemoteFunctions<RemoteFunctions> & BirpcGroupReturnBuiltin<RemoteFunctions> : BirpcGroupReturnBuiltin<RemoteFunctions>;
export type BirpcOptions<RemoteFunctions extends object = Record<string, unknown>, LocalFunctions extends object = Record<string, unknown>, Proxify extends boolean = true> = EventOptions<RemoteFunctions, LocalFunctions, Proxify> & ChannelOptions;
export type BirpcResolver<This> = (this: This, _: string, _: (..._: unknown[]) => unknown) => Thenable<((...args: any[]) => any) | undefined>;
export type BirpcReturn<RemoteFunctions extends object = Record<string, unknown>, LocalFunctions extends object = Record<string, unknown>, Proxify extends boolean = true> = Proxify extends true ? ProxifiedRemoteFunctions<RemoteFunctions> & BirpcReturnBuiltin<RemoteFunctions, LocalFunctions> : BirpcReturnBuiltin<RemoteFunctions, LocalFunctions>;
export type PendingCallHandler = (_: Pick<PromiseEntry, 'method' | 'reject'>) => void | Promise<void>;
export type PromisifyFn<T> = ReturnType<T> extends Promise<any> ? T : (...args: ArgumentsType<T>) => Promise<Awaited<ReturnType<T>>>;
export type ProxifiedRemoteFunctions<RemoteFunctions extends object = Record<string, unknown>> = { [K in keyof RemoteFunctions]: BirpcFn<RemoteFunctions[K]>; };
// #endregion

// #region Functions
export declare function createBirpc<RemoteFunctions extends object = Record<string, unknown>, LocalFunctions extends object = Record<string, unknown>, Proxify extends boolean = true>(_: LocalFunctions, _: BirpcOptions<RemoteFunctions, LocalFunctions, Proxify>): BirpcReturn<RemoteFunctions, LocalFunctions, Proxify>;
export declare function createBirpcGroup<RemoteFunctions extends object = Record<string, unknown>, LocalFunctions extends object = Record<string, unknown>, Proxify extends boolean = true>(_: LocalFunctions, _: ChannelOptions[] | (() => ChannelOptions[]), _?: EventOptions<RemoteFunctions, LocalFunctions, Proxify>): BirpcGroup<RemoteFunctions, LocalFunctions, Proxify>;
// #endregion